use_frameworks!

platform :ios, '10.0'

target 'TestManager_Example' do
  pod 'TestManager', :path => '../'

  target 'TestManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
